### ISSUE TITLE
Add provisiong for volumes with CRD

### ISSUE THREAD

**Issue by danielr1996** [syself/cluster-api-provider-hetzner#1093]
/kind feature

**Describe the solution you'd like**
To dynamically create volumes alongside the HCloudMachines I'd like to have a HCLoudVolume CRD that I can use to declaretively provision and attach a Volume to the worker nodes

**Anything else you would like to add:**
The usecase behind this feature request is the following. I'd like to use longhorn as my storage backend (the hcloud csi driver doesnt support proper backup to an external destination, which longhorn does). But unfortunatelly longhorn can only use storage that is directly available in the host os, therefore I'd like to dynamically provision my volumes for longhorn

**Comment by guettli** [comment]
@danielr1996 We would like to understand your use-case better. Here are some questions:

Where do you want to store the data? Inside the root directory of the hcloud VM, or on a mounted [hcloud volume](https://docs.hetzner.com/cloud/volumes/overview)?

If you want to use the local drive, why does [TopoLVM](https://github.com/topolvm/topolvm) or [open-local](https://github.com/alibaba/open-local) not work for you?

What kind of values do you want to configure in the yaml of the CRD you want to suggest? Maybe provide an example, so that we understand what your desired state looks like.

**Comment by danielr1996** [comment]
I want to store the data in the hcloud volumes, havent used TopoLVM or open local, but if I understand correctly they still need storage that is mounted inside the host, right? So in this sense longhorn, openlocal, TopoLVM are all the same. I also cannot use the systems root disk because it's simply to small

**Comment by danielr1996** [comment]
The baremetal servers don't do it for me, their too expensive and too slow to provision. I want that cheap fast cloud experience. The difference between the pulumi solution / what I want and the csi driver is that the first provisions storage that is mounted to the host, the second provisions storage as persistent volumes in kubernetes. Allowing users to attach volumes to the host directly allowes them to install basically any csi driver they want, because almost all of them need locally attached storage.

I do not want to use the hcloud csi driver because it has no builtin backup, which longhorn does.

**Comment by guettli** [comment]
We don't plan to write a better CSI driver.

Is there already a corresponding feature request in the hcloud CSI driver repo?

If not, then I suggest that you create it.

Sorry, we can't help you here.
