### ISSUE TITLE
ccm-hetzner is failing to start

### ISSUE THREAD

**Issue by Aman1994** [syself/cluster-api-provider-hetzner#1476]
/kind bug

**What steps did you take and what happened:**
Error: secret "capi-cluster-hetzner" not found 

**What did you expect to happen:**
Expected the pods to run but instead it fails with . It was getting created automatically before . This secret is indeed present in my management cluster and was getting copied to my workload cluster automatically and I could see that in `kube-system` NS - but it doesn't get created anymore.  

```
Error: secret "capi-cluster-hetzner" not found 
```

**Environment:**

- cluster-api-provider-hetzner version: latest
- Kubernetes version: 1.29.3
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04

**Comment by guettli** [comment]
Please elaborate where you get this error message.

Maybe the secret is in the wrong namespace? Try `kubectl get secret -A`

Can you please run this tool to see which Conditions indicate an unhealthy state:

```
go run github.com/guettli/check-conditions@latest all
```

What do you mean with "but it doesn't get created anymore."?

Where do you define the string "capi-cluster-hetzner" (because we don't use a secret with that name by default)?

**Comment by janiskemper** [comment]
closing this. Feel free to re-open!
