### ISSUE TITLE
Thoughts using Kubernetes/Rook on Dedicated root servers to create Ceph RBDs and using those RBDs as PVs?

### ISSUE THREAD

**Issue by gc-ss** [syself/cluster-api-provider-hetzner#179]
Now that we have Kubernetes support for Dedicated root servers, are there:
- any thoughts on deploying Rook Ceph RBDs and using those RBDs as PVs?
- anyone tried this already?

**Comment by batistein** [comment]
We implemented dedicated root servers with exactly this use case in mind. We have also thought about using Longhorn as storage and using the Postgres operator to run, for example, Postgres databases on Hetzner's dedicated server.
In the future we will create documentation around this.
At the moment e2e tests and long term tests for the whole storage lifecycle are still missing, so it is not ready for production yet.
But of course try it out! I would love to hear how it works for you.
Here some information how an upgrade is handeled as this is the most critical part running the storage in Kubernetes.

When a server is updated, it is deleted according to the cluster-api logic and a new one is created. As we have [decoupled this ](https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-host.md)and also specify the OS disk via the WWN, the cluster-api would delete the server, but this is no more than removing it from Kubernetes. The server remains the same as before, no data is deleted. Now when the server is selected again, the same OS disk is used, data is deleted on that disk and the server is added to the Kubernetes cluster again. Since no data is deleted on the other hard disks, it should be possible to inform the storage backend so that no rebalancing would be necessary as with a new server.

**Comment by bnerd** [comment]
We're running similar setups on Hetzner since more than 1.5 years in production.

* Hetzner Cloud: Control Plane Nodes
* Hetzner Bare Metal: Worker Nodes

and

* Storage: Rook.io (Ceph)
* Load Balancer: Metal LB
* Postgres Operator (Zalando) for DBs
* …

**Comment by gc-ss** [comment]
@bnerd this is fantastic news! Thank You for sharing.

I can reach out offline if it's better, but:

1. Are you able to run PostgreSQL in HA?
2. Are the PostgreSQL DBs backed by Ceph RBD or you do streaming replication to PVs while the DBs are backed by local SSDs
3. Is the Zalando Postgres Operator able to setup PostgreSQL in HA without you explicitly having to do it using one of the popular PostgreSQL HA tools like Patroni (i.e. the Zalando Postgres Operator really makes the Patroni integration smooth and seamless without needing you to be intimately familiar with the details of Patroni)?

My immediate focus is to setup:

a. HA etcd
b. HA PostgreSQL (for use by Temporal.io)

**Comment by bnerd** [comment]
> 1. Are you able to run PostgreSQL in HA?

Sure.

> 2. Are the PostgreSQL DBs backed by Ceph RBD or you do streaming replication to PVs while the DBs are backed by local SSDs

We run PostgreSQL in HA with Zalando Postgres Operator. Regarding the PV type; that solely depends on your IO requirements. 

We have both types of setups:

* Postgres Operator with Local SSDs (backed by Ceph with NVMe SSDs)
* Postgres Operator with Ceph RBD (backed by local NVMe SSDs directly from the Worker Nods)

For the operator it's just a matter of the Storage Class you provide when creating the DBs. Just ensure the you use reasonable Affinity/Anti-Affinity rules for the Pods.

* https://github.com/zalando/postgres-operator/blob/master/docs/reference/cluster_manifest.md#volume-properties

Both PV types are imho "safe" to use since your dealing with a Cluster Setup. Especially if you ship WALs to e.g. S3 and enable Logical Backups.

> 3. Is the Zalando Postgres Operator able to setup PostgreSQL in HA without you explicitly having to do it using one of the popular PostgreSQL HA tools like Patroni (i.e. the Zalando Postgres Operator really makes the Patroni integration smooth and seamless without needing you to be intimately familiar with the details of Patroni)?

Yes, the Operator uses Patroni internally. The integration is pretty smooth and transparent. You do not need to know much about Patroni etc. to get a DB cluster running initially. Of course there are some situations when you'll have to deal with `patronictl` directly, e.g. `reinit` of a node after failure and so forth.

> My immediate focus is to setup:
> a. HA etcd
> b. HA PostgreSQL (for use by Temporal.io)

That's definitely possible with above mentioned tools! If you like you we can discuss this in more depth offline.

**Comment by gc-ss** [comment]
> If you like you we can discuss this in more depth offline.

I really appreciate you taking your time to read the details and responding.

I have sent you an email from my personal account - please take your time to respond, no rush!

**Comment by KlavsKlavsen** [comment]
We are running k8s clusters, run up by puppet currently, which are setup like this:
software raid 1 on nvme disks (fast but smaller) and on hdd disks (slow but large)
we then setup rook/ceph to use HDD (with 1gb interface, fast disks is not gonna work anyways for ceph) - and then we setup localzfs storageclass for nvme disks, and use those for HA postgres-operator clusters (with HA in operator it handles failover and data sync in app - so local disk is best and fast).

I am trying to figure out, how to use this to roll out such a cluster setup on 3 new bare metal servers with hetzner.. ?
