### ISSUE TITLE
Breaking changes documentation

### ISSUE THREAD

**Issue by CiiDyR** [syself/cluster-api-provider-hetzner#181]
First off, thanks a bunch for the amazing work on this cluster api provider!
We're using alpha.13 for our development clusters, at so far it's been pretty awesome in tandem with talos!
I was considering using this to spin up a new production cluster, however I saw that there are some Breaking changes from .16 to .17, but I wasn't able to see what was needed to be done in order to migrate from an older version from .13 to .17 :-)

Is there any way to figure out what the breaking change is?

Thanks!

**Comment by batistein** [comment]
Hello, unfortunately it is not possible to migrate from v1.0.0-alpha.13 to v1.0.0-alpha.17. We have added the bare metal support, which required to change something in the status of the HetznerCluster object. Bare metal servers have to be added as IP targets - before we had only server targets. This is why we had to change the array of strings to an array of objects.
Since we did not want to do a separate API version, there is no way of migrating this.

Here the change: https://github.com/syself/cluster-api-provider-hetzner/compare/v1.0.0-alpha.16...v1.0.0-alpha.17/#diff-964de9482de3e9bdd98a2e17c86bbc25650afa8b719a4c42a2a0014fc3b1869d

For the future, I can only say that we completed all planned features. We have gotten enough feedback from the community to move the project into beta phase soon. Then there will not be any breaking changes without a migration path.
